

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t15-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api10.my-points.ru
    - web10.my-points.ru
    - insights10.my-points.ru
    secretName: serverpod-tls-t15
  rules:
  - host: "api10.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t15-server-service
            port:
              name: api
  - host: "web10.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t15-server-service
            port:
              name: web
  - host: "insights10.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t15-server-service
            port:
              name: insights
    